----------------------------
token_vuln.php
----------------------------
<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $email = $_POST['email'];

    // VULNERABILITY: Generating a sensitive token using predictable PRNGs.
    // uniqid() is based strictly on the current system time in microseconds.
    // mt_rand() uses the Mersenne Twister algorithm, which leaks its internal state after observing 624 outputs.
    $weak_token = md5(uniqid(mt_rand(), true));

    echo "<div style='border:2px dashed red; padding:15px; background:#fff5f5;'>";
    echo "<h3>Password Reset Initialized!</h3>";
    echo "<p>An email has been dispatched to: <strong>" . htmlspecialchars($email) . "</strong></p>";
    echo "<p><strong>Generated Link (Vulnerable):</strong><br>";
    echo "<code>http://localhost/reset.php?token=" . $weak_token . "</code></p>";
    echo "</div>";
}
?>

<!DOCTYPE html>
<html>
<body>
    <h2>Forgot Password Service</h2>
    <form method="POST">
        <label>Enter your corporate email address:</label><br>
        <input type="email" name="email" placeholder="employee@corporate.local" style="width: 250px;" required><br><br>
        <input type="submit" value="Request Password Reset">
    </form>
</body>
</html>


--------------------------------
How it works
--------------------------------

Test Case 1: Testing for Predictability
Action: Open token_vuln.php in your browser. Click the button 3 or 4 times rapidly. Note down the structure of the resulting MD5 hash tokens.

The Vulnerability: Because uniqid() is based on the system server time, tokens generated within the same second or millisecond have high mathematical correlation. If an attacker knows the approximate time a high-profile target requested a password reset, the search space to brute-force the valid token shrinks drastically.

Test Case 2: Mersenne Twister State Crack
The Attack: The mt_rand() function is entirely deterministic. If an attacker can see several tokens generated by the server (e.g., by creating multiple dummy accounts and requesting resets), they can feed those values into publicly available tools (like php_mt_seed).

The Impact: The tool calculates the exact initial seed used by the server's PHP engine. 
Once the attacker knows the seed, they can perfectly calculate all future random numbers that the server will ever generate. They can trigger a password reset for the admin@corporate.local user, predict the resulting token instantly without checking their email, and hijack the administrator account.






--------------------------------
token_secure.php
--------------------------------
<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $email = $_POST['email'];

    // PATCH: Utilize a CSPRNG function to generate high-entropy bytes
    // random_bytes(32) generates a completely unpredictable 32-byte raw binary string.
    try {
        $crypto_strong_bytes = random_bytes(32);
        
        // Convert the binary stream into a clean, safe hexadecimal string for URL usage
        $secure_token = bin2hex($crypto_strong_bytes);
        
    } catch (Exception $e) {
        // Safe fallback in case the system kernel fails to provide adequate entropy
        die("Cryptographic Error: Insufficient system entropy available.");
    }

    echo "<div style='border:2px solid green; padding:15px; background:#f5fff5;'>";
    echo "<h3>Password Reset Initialized Safely!</h3>";
    echo "<p>An email has been dispatched to: <strong>" . htmlspecialchars($email) . "</strong></p>";
    echo "<p><strong>Generated Link (Secure):</strong><br>";
    echo "<code style='word-break: break-all;'>http://localhost/reset.php?token=" . $secure_token . "</code></p>";
    echo "</div>";
}
?>

<!DOCTYPE html>
<html>
<body>
    <h2>Forgot Password Service (Secure)</h2>
    <form method="POST">
        <label>Enter your corporate email address:</label><br>
        <input type="email" name="email" placeholder="employee@corporate.local" style="width: 250px;" required><br><br>
        <input type="submit" value="Request Password Reset">
    </form>
</body>
</html>
